=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="RequiredString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataFormatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="XML"/>
			<xs:enumeration value="TEXT"/>
			<xs:enumeration value="CSV"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SystemEnvironmentType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Development"/>
			<xs:enumeration value="Test"/>
			<xs:enumeration value="Production"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LoggingLevelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FINEST"/>
			<xs:enumeration value="FINER"/>
			<xs:enumeration value="FINE"/>
			<xs:enumeration value="CONFIG"/>
			<xs:enumeration value="INFO"/>
			<xs:enumeration value="WARNING"/>
			<xs:enumeration value="SEVERE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ActionOnErrorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="shutdown"/>
			<xs:enumeration value="discard"/>
			<xs:enumeration value="none"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SchemaValidationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="off"/>
			<xs:enumeration value="on"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Action_On_ErrorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RESPOND"/>
			<xs:enumeration value="EXCEPTION"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Immediate_CommitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="YES"/>
			<xs:enumeration value="NO"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DbActionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="insert"/>
			<xs:enumeration value="update"/>
			<xs:enumeration value="delete"/>
			<xs:enumeration value="select"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Applic">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Params" minOccurs="0">
					<xs:complexType>
						<xs:all>
							<xs:element name="ExternalShell" type="RequiredString" minOccurs="1"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="Input">
					<xs:complexType>
						<xs:all>
							<xs:element name="InputSource">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="InputLimit" type="xs:positiveInteger" minOccurs="0"/>
										<xs:element name="DataFormat" type="DataFormatType" />
										<xs:element name="DataContractName" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="RequiredString">
														<xs:attribute name="Location" type="xs:string" use="required"/>
														<xs:attribute name="ActionOnError" type="ActionOnErrorType" default="shutdown"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:choice minOccurs="0">
											<xs:element name="InputQueue">
												<xs:complexType>
													<xs:all>
														<xs:element name="UrlJMSserver" type="RequiredString" minOccurs="0"/>
														<xs:element name="QueueName" type="RequiredString" />
														<xs:element name="MilliSecondsBeforeQuiet" type="xs:positiveInteger" minOccurs="0"/>
													</xs:all>
												</xs:complexType>
											</xs:element>
											<xs:element name="InputSocket">
												<xs:complexType>
													<xs:all>
														<xs:element name="PortNumber" type="xs:positiveInteger"/>
													</xs:all>
												</xs:complexType>
											</xs:element>
											<xs:element name="InputFile">
												<xs:complexType>
													<xs:all>
														<xs:element name="FileNameFilter" type="RequiredString"/>
														<xs:element name="FileDir" type="RequiredString" minOccurs="0"/>
														<xs:element name="SortFilteredFileNames" type="xs:boolean" minOccurs="0" default="true"/>
														<xs:element name="CSVParams" minOccurs="0">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="FieldSeparator" type="RequiredString" minOccurs="0"/>
																	<xs:element name="MaxRecsPerMessage" type="xs:positiveInteger" minOccurs="0"/>
																	<xs:element name="NumRecordsToSkip" type="xs:positiveInteger" minOccurs="0"/>
																	<xs:element name="ColumnOrder">
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="Column" type="RequiredString" minOccurs="1" maxOccurs="unbounded"/>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																	<xs:element name="XMLFormat" type="DbActionType"/>
																	<xs:element name="InsertParams" minOccurs="0">
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="Action_On_Error" type="Action_On_ErrorType" minOccurs="0"/>
																				<xs:element name="Prepared_Statement_Name" type="RequiredString" minOccurs="0"/>
																				<xs:element name="Immediate_Commit" type="Immediate_CommitType" minOccurs="0"/>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:all>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="InputValidation" minOccurs = "0">
								<xs:complexType>
									<xs:attribute name="SchemaValidation" type="SchemaValidationType" default="off"/>
									<xs:attribute name="SchemaDefinitionFileName" type="RequiredString"/>
									<xs:attribute name="SchemaLanguage" type="RequiredString" default="http://www.w3.org/2001/XMLSchema"/>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="Output" minOccurs="0">
					<xs:complexType>
						<xs:choice>
							<xs:element name="OutputQueue">
								<xs:complexType>
									<xs:all>
										<xs:element name="UrlJMSserver" type="RequiredString" minOccurs="0"/>
										<xs:element name="QueueName" type="RequiredString"/>
										<xs:element name="ReplyToQueueName" type="RequiredString" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="OutputFile">
								<xs:complexType>
									<xs:all>
										<xs:element name="FileNameTemplate" type="RequiredString" />
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="OutputHTTP">
								<xs:complexType>
									<xs:all>
										<xs:element name="ServerUrl" type="RequiredString"/>
										<xs:element name="EndPointName" type="RequiredString"/>
										<xs:element name="HTTPWithBackoff" type="xs:boolean" minOccurs="0" default="true"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="Processing">
					<xs:complexType>
						<xs:all>
							<xs:element name="MessageProcessingClassName" type="RequiredString"/>
							<xs:element name="MessageProcessingSettingsFileName" type="RequiredString" minOccurs="0"/>
							<xs:element name="MinResponsesExpected" type="xs:integer" minOccurs="0"/>
							<xs:element name="MindElements" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ElementName" type="RequiredString" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="SendElements">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ElementName" type="RequiredString" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="TargetMainDocElementName" type="RequiredString" minOccurs="0"  default="MESSAGE"/>
							<xs:element name="ResponseMainDocElementName" type="RequiredString" minOccurs="0"  default="MESSAGE"/>
							<xs:element name="ResponseLiterals" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ResponseLiteral" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="RequiredString">
														<xs:attribute name="Location" type="xs:string" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="Auditing" minOccurs="0">
					<xs:complexType>
						<xs:all>
							<xs:element name="AuditKeys" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="KeyName" type="RequiredString" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="ActionOnError" type="ActionOnErrorType" default="none"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="AuditKeysSeparator" type="RequiredString" minOccurs="0"/>
							<xs:element name="ErrorFiles" minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="ErrorFilesDir" type="RequiredString" minOccurs="0"/>
										<xs:element name="ErrorFileNameTemplate" type="RequiredString" minOccurs="0"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="Logging">
					<xs:complexType>
						<xs:all>
							<xs:element name="Level" minOccurs="0">
								<xs:complexType>
									<xs:choice>
										<xs:element name="EnvironmentLoggingLevel" type="SystemEnvironmentType"/>
										<xs:element name="GeneralLoggingLevel" type="LoggingLevelType"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="LogFileDir" type="RequiredString" minOccurs="0"/>
							<xs:element name="LogFileNameTemplate" type="RequiredString" minOccurs="0"/>
							<xs:element name="ShutDownLogFileNameTemplate" type="RequiredString" minOccurs="0"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_CtoH.xml
<?xml version="1.0" encoding="UTF-8"?>
DIDN'T GET THIS WORKING - taking data from CSV file creates a Db shape XML msg
<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<InputLimit>1</InputLimit>
			<DataFormat>CSV</DataFormat>
			<InputFile>
				<FileDir>D:\eclipseWorkspaces\workspace\GeMHa\data\</FileDir>
				<FileNameFilter>Batchuler_Failure_Report_CSV_[0-9]*.txt</FileNameFilter>
				<CSVParams>
					<FieldSeparator>\t</FieldSeparator>
					<MaxRecsPerMessage>1</MaxRecsPerMessage>
					<ColumnOrder>
						<Column>ERRORID</Column>
						<Column>ERRORCODE</Column>
						<Column>ERRORSUBCODE</Column>
						<Column>NOTIFICATIONMESSAGE</Column>
					</ColumnOrder>
					<XMLFormat>insert</XMLFormat>
				</CSVParams>
			</InputFile>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="/mv1/delv/middleware/CRDB/apps/mqXmq/data/sorts_transfer_service_order_to_delivery.xsd"/>
	</Input>
	<Output>
<!-- 
		<OutputHTTP>
			<ServerUrl>HTTP://localhost:8080</ServerUrl>
			<EndPointName>RegisterNotifiedDeviceServlet</EndPointName>
		</OutputHTTP>
 -->
		<OutputFile>
			<FileNameTemplate>responses/response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>gemha.servers.LwProcessMessageDoNothing</MessageProcessingClassName>
				<ResponseMainDocElementName>RexRunNotification</ResponseMainDocElementName>
		<SendElements>
			<ElementName>/MESSAGE/DBACTION</ElementName>
		</SendElements>
<!-- 
		<ResponseLiterals>
			<ResponseLiteral Location='/RexRunNotification/TargetApplicationName'>RexBark</ResponseLiteral>
			<ResponseLiteral Location='/RexRunNotification/Source'>batchuler</ResponseLiteral>
			<ResponseLiteral Location='/RexRunNotification/SourceMsgType'>error</ResponseLiteral>
			<ResponseLiteral Location='/RexRunNotification/RecipientList'>ingelsc;wadel</ResponseLiteral>
		</ResponseLiterals>
 -->
	</Processing>
	<Auditing>
		<AuditKeys ActionOnError="shutdown">
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/ERRORID</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>FINEST</GeneralLoggingLevel>
		</Level>
		<LogFileDir>D:\eclipseWorkspaces\workspace\GeMHa\logs\</LogFileDir>
		<LogFileNameTemplate>LwGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>LwGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_OtoDBtoO.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<DataFormat>XML</DataFormat>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="C:\Users\wadel\git\GeMHa\GeMHa\someMessage.xsd"/>
	</Input>
	<Processing>
		<MessageProcessingClassName>gemha.servers.LwProcessMessageForDb</MessageProcessingClassName>
		<MessageProcessingSettingsFileName>C:\Users\wadel\git\GeMHa\GeMHa\ApplicSettingsFiles\LwProcessMessageForDbSettings.xml</MessageProcessingSettingsFileName>
		<MindElements>
			<ElementName>/MESSAGE/DBACTION/KEY</ElementName>
		</MindElements>
		<SendElements>
			<ElementName>/MESSAGE/DBACTION</ElementName>
		</SendElements>
	</Processing>
	<Auditing>
		<AuditKeys ActionOnError="shutdown">
			<KeyName>/MESSAGE/DBACTION/KEY</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
		<ErrorFiles>
			<ErrorFilesDir>C:\Users\wadel\git\GeMHa\GeMHa\errors\</ErrorFilesDir>
			<ErrorFileNameTemplate>ErrorMessage_*_?.xml</ErrorFileNameTemplate>
		</ErrorFiles>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>FINEST</GeneralLoggingLevel>
		</Level>
		<LogFileDir>C:\Users\wadel\git\GeMHa\GeMHa\logs\</LogFileDir>
		<LogFileNameTemplate>LwGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>LwGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Applic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
  <Params>
    <ExternalShell>ExternalShell</ExternalShell>
  </Params>
  <Input>
    <InputSource>
      <DataFormat>XML</DataFormat>
    </InputSource>
  </Input>
  <Output>
    <OutputQueue>
      <QueueName>QueueName</QueueName>
    </OutputQueue>
  </Output>
  <Processing>
    <MessageProcessingClassName>MessageProcessingClassName</MessageProcessingClassName>
    <SendElements>
      <ElementName>ElementName</ElementName>
    </SendElements>
  </Processing>
  <Auditing/>
  <Logging/>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_QtoF.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<InputLimit>6</InputLimit>
			<DataFormat>XML</DataFormat>
			<InputQueue>
				<UrlJMSserver>failover://tcp://localhost:61616</UrlJMSserver>
				<QueueName>SendReceiveQueue</QueueName>
				<MilliSecondsBeforeQuiet>3000</MilliSecondsBeforeQuiet>
			</InputQueue>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="/mv1/delv/middleware/CRDB/apps/mqXmq/data/sorts_transfer_service_order_to_delivery.xsd"/>
	</Input>
	<Output>
		<OutputFile>
			<FileNameTemplate>C:\Users\wadel\workspace\GeMHa\responses\response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>gemha.servers.LwProcessMessageDoNothing</MessageProcessingClassName>
		<MindElements>
			<ElementName>MESSAGE/C0</ElementName>
			<ElementName>MESSAGE/XBCCTL</ElementName>
		</MindElements>
		<SendElements>
			<ElementName>MESSAGE/DELV/ORD</ElementName>
		</SendElements>
		<TargetMainDocElementName>TIS_REQUEST</TargetMainDocElementName>
		<ResponseMainDocElementName>MESSAGE_RESPONSE</ResponseMainDocElementName>
		<ResponseLiterals>
			<ResponseLiteral Location="MESSAGE_RESPONSE/C0/TSYS">TIS</ResponseLiteral>
			<ResponseLiteral Location="MESSAGE_RESPONSE/C0/RSYS">BND</ResponseLiteral>
		</ResponseLiterals>
	</Processing>
	<Auditing>
		<AuditKeys>
			<KeyName>MESSAGE/DELV/ORD/SERVICE_ORDER_NUMBER</KeyName>
			<KeyName>MESSAGE/DELV/ORD/MAIN_NATIONAL_DEST_CODE</KeyName>
			<KeyName>MESSAGE/DELV/ORD/MAIN_TELEPHONE_NO</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<EnvironmentLoggingLevel>Development</EnvironmentLoggingLevel>
		</Level>
		<LogFileDir>C:\Users\wadel\workspace\GeMHa\logs\</LogFileDir>
		<LogFileNameTemplate>LwGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>LwGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_CtoDBtoF.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<InputLimit>7</InputLimit>
			<DataFormat>CSV</DataFormat>
			<InputFile>
				<FileDir>data/</FileDir>
				<FileNameFilter>input_CSV_[0-9]*.txt</FileNameFilter>
				<CSVParams>
					<FieldSeparator>\t</FieldSeparator>
					<MaxRecsPerMessage>2</MaxRecsPerMessage>
					<ColumnOrder>
						<Column>USERID</Column>
						<Column>USERCODENAME</Column>
						<Column>USERSTATUS</Column>
						<Column>ADMINCOMMENT</Column>
						<Column>UPDATEDATETIME</Column>
					</ColumnOrder>
					<XMLFormat>insert</XMLFormat>
					<InsertParams>
						<Action_On_Error>RESPOND</Action_On_Error>
						<Immediate_Commit>YES</Immediate_Commit>
					</InsertParams>
				</CSVParams>
			</InputFile>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="/mv1/delv/middleware/CRDB/apps/mqXmq/data/sorts_transfer_service_order_to_delivery.xsd"/>
	</Input>
	<Output>
		<OutputFile>
			<FileNameTemplate>response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>EirProcessMessageForDb</MessageProcessingClassName>
		<MessageProcessingSettingsFileName>EirProcessMessageForDbSettings.xml</MessageProcessingSettingsFileName>
		<SendElements>
			<ElementName>/MESSAGE/DBACTION</ElementName>
		</SendElements>
	</Processing>
	<Auditing>
		<AuditKeys>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERID</KeyName>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>FINEST</GeneralLoggingLevel>
		</Level>
		<LogFileDir>/mv1/delv/middleware/CRDB/apps/mqXmq/</LogFileDir>
		<LogFileNameTemplate>EirGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>EirGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_FtoFtoF.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Input>
		<InputSource>
			<DataFormat>XML</DataFormat>
			<InputFile>
				<FileDir>data/</FileDir>
				<FileNameFilter>fileme_001.xml</FileNameFilter>
			</InputFile>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="C:\Users\wadel\git\GeMHa\GeMHa\someMessage.xsd"/>
	</Input>
	<Output>
		<OutputFile>
			<FileNameTemplate>responses/response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>gemha.servers.LwProcessMessageForFile</MessageProcessingClassName>
		<MessageProcessingSettingsFileName>ApplicSettingsFiles/LwProcessMessageForFileSettings.xml</MessageProcessingSettingsFileName>
		<SendElements>
			<ElementName>/xxxMESSAGE/FILE_REQUEST</ElementName>
		</SendElements>
	</Processing>
	<Auditing>
		<AuditKeys>
			<KeyName>/xxxMESSAGE/FILE_REQUEST/KEY</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>CONFIG</GeneralLoggingLevel>
		</Level>
		<LogFileDir>logs\</LogFileDir>
		<LogFileNameTemplate>LwGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>LwGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_CtoStoF.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<InputLimit>7</InputLimit>
			<DataFormat>CSV</DataFormat>
			<InputFile>
				<FileDir>C:\Users\wadel\workspace\GeMHa\data\</FileDir>
				<FileNameFilter>input_CSV_[0-9]*.txt</FileNameFilter>
				<CSVParams>
					<FieldSeparator>\t</FieldSeparator>
					<MaxRecsPerMessage>2</MaxRecsPerMessage>
					<NumRecordsToSkip>1</NumRecordsToSkip>
					<ColumnOrder>
						<Column>USERID</Column>
						<Column>USERCODENAME</Column>
						<Column>USERSTATUS</Column>
						<Column>ADMINCOMMENT</Column>
						<Column>UPDATEDATETIME</Column>
					</ColumnOrder>
					<XMLFormat>insert</XMLFormat>
					<InsertParams>
						<Action_On_Error>EXCEPTION</Action_On_Error>
						<Prepared_Statement_Name>LW_delme1_insert_001</Prepared_Statement_Name>
						<Immediate_Commit>YES</Immediate_Commit>
					</InsertParams>
				</CSVParams>
			</InputFile>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="/mv1/delv/middleware/CRDB/apps/mqXmq/data/sorts_transfer_service_order_to_delivery.xsd"/>
	</Input>
	<Output>
		<OutputFile>
			<FileNameTemplate>response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>gemha.servers.LwProcessMessageForSocket</MessageProcessingClassName>
		<MessageProcessingSettingsFileName>C:\Users\wadel\workspace\GeMHa\ApplicSettingsFiles\LwProcessMessageForSocketSettings.xml</MessageProcessingSettingsFileName>
		<SendElements>
			<ElementName>/MESSAGE/DBACTION</ElementName>
		</SendElements>
	</Processing>
	<Auditing>
		<AuditKeys>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERID</KeyName>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>FINEST</GeneralLoggingLevel>
		</Level>
		<LogFileDir>C:\Users\wadel\workspace\GeMHa\logs\</LogFileDir>
		<LogFileNameTemplate>LwGenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>LwGenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/Applic_CtoF.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Oct 14 15:42:17 BST 2008 -->

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Applic.xsd">
	<Params>
		<ExternalShell>sh</ExternalShell>
	</Params>
	<Input>
		<InputSource>
			<InputLimit>7</InputLimit>
			<DataFormat>CSV</DataFormat>
			<InputFile>
				<FileDir>data\</FileDir>
				<FileNameFilter>input_CSV_[0-9]*.txt</FileNameFilter>
				<CSVParams>
					<FieldSeparator>\t</FieldSeparator>
					<MaxRecsPerMessage>2</MaxRecsPerMessage>
					<NumRecordsToSkip>1</NumRecordsToSkip>
					<ColumnOrder>
						<Column>USERID</Column>
						<Column>USERCODENAME</Column>
						<Column>USERSTATUS</Column>
						<Column>ADMINCOMMENT</Column>
						<Column>UPDATEDATETIME</Column>
					</ColumnOrder>
					<XMLFormat>insert</XMLFormat>
					<InsertParams>
						<Action_On_Error>EXCEPTION</Action_On_Error>
						<Prepared_Statement_Name>LW_delme1_insert_001</Prepared_Statement_Name>
						<Immediate_Commit>true</Immediate_Commit>
					</InsertParams>
				</CSVParams>
			</InputFile>
		</InputSource>
		<InputValidation SchemaValidation="off" SchemaDefinitionFileName="C:\Users\wadel\git\GeMHa\GeMHa\someMessage.xsd"/>
	</Input>
	<Output>
		<OutputFile>
			<FileNameTemplate>responses/response_*_?.xml</FileNameTemplate>
		</OutputFile>
	</Output>
	<Processing>
		<MessageProcessingClassName>gemha.servers.ProcessMessageDoNothing</MessageProcessingClassName>
		<SendElements>
			<ElementName>/MESSAGE/DBACTION</ElementName>
		</SendElements>
	</Processing>
	<Auditing>
		<AuditKeys>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERID</KeyName>
			<KeyName>/MESSAGE/DBACTION/INSERT/COLUMNS/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
	<Logging>
		<Level>
			<GeneralLoggingLevel>FINEST</GeneralLoggingLevel>
		</Level>
		<LogFileDir>logs\</LogFileDir>
		<LogFileNameTemplate>GenericMessageHandler.log</LogFileNameTemplate>
		<ShutDownLogFileNameTemplate>GenericMessageHandler_shutdown.log</ShutDownLogFileNameTemplate>
	</Logging>
</Applic>
