=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/LwProcessMessageForDbSettings.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="RequiredString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UpdateLockingStrategyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="none"/>
			<xs:enumeration value="optimistic"/>
			<xs:enumeration value="pessimistic"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DbActionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="insert"/>
			<xs:enumeration value="update"/>
			<xs:enumeration value="delete"/>
			<xs:enumeration value="select"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SQLReturnTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="COLUMNS"/>
			<xs:enumeration value="XML"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Applic">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Params">
					<xs:complexType>
						<xs:all>
							<xs:element name="JdbcClass" type="RequiredString"/>
							<xs:element name="DbURL" type="RequiredString"/>
							<xs:element name="UserName" type="RequiredString" minOccurs="0"/>
							<xs:element name="UserPass" type="RequiredString" minOccurs="0"/>
							<xs:element name="AutoCommit" type="RequiredString" minOccurs="0"/>
							<xs:element name="DefaultTablename" type="RequiredString" minOccurs="0"/>
							<xs:element name="UpdateLockingStrategy" type="UpdateLockingStrategyType" minOccurs="0"/>
							<xs:element name="DateFormat" type="RequiredString" minOccurs="0"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="PreparedStatements" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PreparedStatement" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="PreparedStatementName" type="RequiredString"/>
										<xs:element name="PreparedStatementSQL" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="RequiredString">
														<xs:attribute name="ReturnType" type="SQLReturnTypeType" default="COLUMNS"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="ParameterOrder">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Column" type="RequiredString" minOccurs="1" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Auditing" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AuditKeys" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="KeyName" type="RequiredString" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="DbAction" type="DbActionType"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="AuditKeysSeparator" type="RequiredString" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/LwProcessMessageForDbSettings_Load_Contacts.xml
<?xml version="1.0" encoding="UTF-8"?>

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LwProcessMessageForDbSettings.xsd">
	<Params>
<!--	Oracle connection over JDBC...
		<JdbcClass>oracle.jdbc.driver.OracleDriver</JdbcClass>
		<DbURL>jdbc:oracle:thin:@localhost:1521:DR2D</DbURL>
  -->
<!--	Derby Jdbc EmbeddedDriver in C:\glassfish3\javadb\lib\derby.jar
		Derby Jdbc ClientDriver   in C:\glassfish3\javadb\lib\derbyclient.jar
 -->
		<JdbcClass>org.apache.derby.jdbc.ClientDriver</JdbcClass>
		<DbURL>jdbc:derby://localhost:1527/lw_contacts</DbURL>
  		<UserName>APP</UserName>
		<UserPass>APP</UserPass>
		<AutoCommit>off</AutoCommit>
		<DefaultTablename>CONTACT_ALL</DefaultTablename>
		<UpdateLockingStrategy>none</UpdateLockingStrategy>
<!--
		Only needed for Oracle...
		<DateFormat>YYYY-MM-DD</DateFormat>
 -->
	</Params>
	<PreparedStatements>
		<PreparedStatement>
			<PreparedStatementName>CONTACT_ALL_insert_001</PreparedStatementName>
			<PreparedStatementSQL>INSERT INTO CONTACT_ALL (NAME,GIVEN_NAME,ADDITIONAL_NAME,FAMILY_NAME,YOMI_NAME,NOTES,GROUP_MEMBERSHIP,EMAIL_1_TYPE,EMAIL_1_VALUE,EMAIL_2_TYPE,EMAIL_2_VALUE,PHONE_1_TYPE,PHONE_1_VALUE,PHONE_2_TYPE,PHONE_2_VALUE) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)</PreparedStatementSQL>
			<ParameterOrder>
				<Column>NAME</Column>
				<Column>GIVEN_NAME</Column>
				<Column>ADDITIONAL_NAME</Column>
				<Column>FAMILY_NAME</Column>
				<Column>YOMI_NAME</Column>
				<Column>NOTES</Column>
				<Column>GROUP_MEMBERSHIP</Column>
				<Column>EMAIL_1_TYPE</Column>
				<Column>EMAIL_1_VALUE</Column>
				<Column>EMAIL_2_TYPE</Column>
				<Column>EMAIL_2_VALUE</Column>
				<Column>PHONE_1_TYPE</Column>
				<Column>PHONE_1_VALUE</Column>
				<Column>PHONE_2_TYPE</Column>
				<Column>PHONE_2_VALUE</Column>
			</ParameterOrder>
		</PreparedStatement>
<!-- 	This is an Oracle-specific type query
		<PreparedStatement>
			<PreparedStatementName>LW_delme1_select_002</PreparedStatementName>
			<PreparedStatementSQL ReturnType="XML">SELECT XMLElement("USER",XMLAttributes(userid), XMLElement("DETAILS", XMLForest(userCodeName,userStatus,adminComment))).getStringVal() AS theXML FROM LW_delme1 WHERE USERSTATUS = ?</PreparedStatementSQL>
			<ParameterOrder>
				<Column>USERSTATUS</Column>
			</ParameterOrder>
		</PreparedStatement>
 -->
	</PreparedStatements>
	<Auditing>
		<AuditKeys DbAction="insert">
			<KeyName>INSERT/COLUMNS/NAME</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
</Applic>

=== wadelts/LwGeMHa/GeMHa/ApplicSettingsFiles/LwProcessMessageForDbSettings.xml
<?xml version="1.0" encoding="UTF-8"?>

<Applic  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LwProcessMessageForDbSettings.xsd">
	<Params>
<!--	Oracle connection over JDBC...
		<JdbcClass>oracle.jdbc.driver.OracleDriver</JdbcClass>
		<DbURL>jdbc:oracle:thin:@localhost:1521:DR2D</DbURL>
  		<UserName>system</UserName>
		<UserPass>manager</UserPass>
  -->
<!--	Derby Jdbc EmbeddedDriver in C:\glassfish3\javadb\lib\derby.jar
		Derby Jdbc ClientDriver   in C:\glassfish3\javadb\lib\derbyclient.jar
 -->
<!--	Derby connection over JDBC Embedded version...
		<JdbcClass>org.apache.derby.jdbc.EmbeddedDriver</JdbcClass>
		<DbURL>jdbc:derby:C:/Users/wadel/DERBYTUTOR/firstdb</DbURL>
 -->
<!--	Derby connection over JDBC - Server version...
		Note: The Derby server doesn't come up automatically with my Glassfish4. 
 -->
<!--
		<JdbcClass>org.apache.derby.jdbc.ClientDriver</JdbcClass>
		<DbURL>jdbc:derby://localhost/lemmo</DbURL>
  		<UserName>APP</UserName>
		<UserPass>APP</UserPass>
 -->
<!--
		User name and password not normally needed for Derby Embedded.
 -->
		<JdbcClass>com.mysql.jdbc.Driver</JdbcClass>
		<DbURL>jdbc:mysql://localhost:3306/users</DbURL>
  		<UserName>corpUser01</UserName>
		<UserPass>dopple66ganger</UserPass>
		
		<!-- Notes for MySQL:
			 Do not incorrectly mix AutoCommit and the IMMEDIATE_COMMIT element of an individual
			 statement. If both are true/on the database will complain, as we cannot explicitly
			 commit when AutoCommit is on. 
			 NEVER use an uppercase letter when creating a table. Even when MySQL tells you not allowed
			 and changes name to lower case, GRANTS are not saved correctly and you keep getting 'insert
			 command denied to user' errors.
		-->
		<AutoCommit>off</AutoCommit>
		<DefaultTablename>users.lw_delme1</DefaultTablename>
		<UpdateLockingStrategy>none</UpdateLockingStrategy>
<!--
		Only needed for Oracle...
		<DateFormat>YYYY-MM-DD</DateFormat>
 -->
	</Params>
	<PreparedStatements>
		<PreparedStatement>
			<PreparedStatementName>LW_delme1_insert_001</PreparedStatementName>
			<PreparedStatementSQL>INSERT INTO users.lw_delme1 (ADMINCOMMENT,USERCODENAME,USERID,USERSTATUS,UPDATEDATETIME) VALUES (?,?,?,?,?)</PreparedStatementSQL>
			<ParameterOrder>
				<Column>ADMINCOMMENT</Column>
				<Column>USERCODENAME</Column>
				<Column>USERID</Column>
				<Column>USERSTATUS</Column>
				<Column>UPDATEDATETIME</Column>
			</ParameterOrder>
		</PreparedStatement>
		<PreparedStatement>
			<PreparedStatementName>LW_delme1_update_001</PreparedStatementName>
			<PreparedStatementSQL>UPDATE users.lw_delme1 SET USERSTATUS = 'ACTIVE' WHERE USERID = ?</PreparedStatementSQL>
			<ParameterOrder>
				<Column>USERID</Column>
			</ParameterOrder>
		</PreparedStatement>
		<PreparedStatement>
			<PreparedStatementName>LW_delme1_select_001</PreparedStatementName>
			<PreparedStatementSQL>SELECT * FROM users.lw_delme1 WHERE USERSTATUS = ?</PreparedStatementSQL>
			<ParameterOrder>
				<Column>USERSTATUS</Column>
			</ParameterOrder>
		</PreparedStatement>
<!-- 	This is an Oracle-specific type query
		<PreparedStatement>
			<PreparedStatementName>LW_delme1_select_002</PreparedStatementName>
			<PreparedStatementSQL ReturnType="XML">SELECT XMLElement("USER",XMLAttributes(userid), XMLElement("DETAILS", XMLForest(userCodeName,userStatus,adminComment))).getStringVal() AS theXML FROM LW_delme1 WHERE USERSTATUS = ?</PreparedStatementSQL>
			<ParameterOrder>
				<Column>USERSTATUS</Column>
			</ParameterOrder>
		</PreparedStatement>
 -->
	</PreparedStatements>
	<Auditing>
		<AuditKeys DbAction="insert">
			<KeyName>INSERT/COLUMNS/USERID</KeyName>
			<KeyName>INSERT/COLUMNS/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeys DbAction="update">
			<KeyName>UPDATE/WHERE/USERID</KeyName>
			<KeyName>UPDATE/WHERE/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeys DbAction="delete">
			<KeyName>DELETE/WHERE/USERID</KeyName>
			<KeyName>DELETE/WHERE/USERCODENAME</KeyName>
		</AuditKeys>
		<AuditKeys DbAction="select">
			<KeyName>SELECT/WHERE/USERSTATUS</KeyName>
		</AuditKeys>
		<AuditKeysSeparator>-</AuditKeysSeparator>
	</Auditing>
</Applic>
